#if !canImport(ObjectiveC)
import XCTest

extension BoxDataSourceTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoxDataSourceTests = [
        ("testCount", testCount),
        ("testDelete", testDelete),
        ("testGet", testGet),
        ("testInsert", testInsert),
        ("testLimit", testLimit),
        ("testReplace", testReplace),
        ("testSelect", testSelect),
        ("testUpdate", testUpdate),
        ("testUpsert", testUpsert),
    ]
}

extension BoxIndexTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoxIndexTests = [
        ("testBitset", testBitset),
        ("testCount", testCount),
        ("testDelete", testDelete),
        ("testGet", testGet),
        ("testHash", testHash),
        ("testInsert", testInsert),
        ("testMany", testMany),
        ("testReplace", testReplace),
        ("testRTree", testRTree),
        ("testSelect", testSelect),
        ("testSequence", testSequence),
        ("testTree", testTree),
        ("testUpdate", testUpdate),
        ("testUpsert", testUpsert),
    ]
}

extension BoxSchemaTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoxSchemaTests = [
        ("testCreateSpace", testCreateSpace),
        ("testSchema", testSchema),
    ]
}

extension BoxSpaceTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoxSpaceTests = [
        ("testCount", testCount),
        ("testDelete", testDelete),
        ("testGet", testGet),
        ("testInsert", testInsert),
        ("testReplace", testReplace),
        ("testSelect", testSelect),
        ("testSequence", testSequence),
        ("testStoreIndex", testStoreIndex),
        ("testUpdate", testUpdate),
        ("testUpsert", testUpsert),
    ]
}

extension BoxTransactionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoxTransactionTests = [
        ("testCommit", testCommit),
        ("testRollback", testRollback),
        ("testTCommit", testTCommit),
        ("testTRollback", testTRollback),
    ]
}

extension BoxTupleTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoxTupleTests = [
        ("testUnpackTuple", testUnpackTuple),
    ]
}

extension DispatchTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DispatchTests = [
        ("testSyncTask", testSyncTask),
    ]
}

extension LuaTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LuaTests = [
        ("testEval", testEval),
        ("testPushPop", testPushPop),
        ("testPushPopArray", testPushPopArray),
        ("testPushPopMany", testPushPopMany),
        ("testPushPopMap", testPushPopMap),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BoxDataSourceTests.__allTests__BoxDataSourceTests),
        testCase(BoxIndexTests.__allTests__BoxIndexTests),
        testCase(BoxSchemaTests.__allTests__BoxSchemaTests),
        testCase(BoxSpaceTests.__allTests__BoxSpaceTests),
        testCase(BoxTransactionTests.__allTests__BoxTransactionTests),
        testCase(BoxTupleTests.__allTests__BoxTupleTests),
        testCase(DispatchTests.__allTests__DispatchTests),
        testCase(LuaTests.__allTests__LuaTests),
    ]
}
#endif
