#if !canImport(ObjectiveC)
import XCTest

extension CHAPSHA1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CHAPSHA1Tests = [
        ("testCHAPSHA1", testCHAPSHA1),
    ]
}

extension IProtoConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IProtoConnectionTests = [
        ("testAuth", testAuth),
        ("testCall", testCall),
        ("testEval", testEval),
        ("testPing", testPing),
        ("testRequest", testRequest),
    ]
}

extension IProtoDataSourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IProtoDataSourceTests = [
        ("testCount", testCount),
        ("testDelete", testDelete),
        ("testGet", testGet),
        ("testInsert", testInsert),
        ("testReplace", testReplace),
        ("testSelect", testSelect),
        ("testUpdate", testUpdate),
        ("testUpsert", testUpsert),
    ]
}

extension IProtoIndexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IProtoIndexTests = [
        ("testArrayPartType", testArrayPartType),
        ("testBitset", testBitset),
        ("testBooleanPartType", testBooleanPartType),
        ("testCount", testCount),
        ("testDelete", testDelete),
        ("testGet", testGet),
        ("testHash", testHash),
        ("testInsert", testInsert),
        ("testIntegerPartType", testIntegerPartType),
        ("testMany", testMany),
        ("testNumberPartType", testNumberPartType),
        ("testReplace", testReplace),
        ("testRTree", testRTree),
        ("testScalarPartType", testScalarPartType),
        ("testSelect", testSelect),
        ("testSequence", testSequence),
        ("testStringPartType", testStringPartType),
        ("testTree", testTree),
        ("testUnsignedPartType", testUnsignedPartType),
        ("testUpdate", testUpdate),
        ("testUppercased", testUppercased),
        ("testUpsert", testUpsert),
    ]
}

extension IProtoIteratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IProtoIteratorTests = [
        ("testSelectAll", testSelectAll),
        ("testSelectEQ", testSelectEQ),
        ("testSelectGE", testSelectGE),
        ("testSelectGT", testSelectGT),
        ("testSelectLE", testSelectLE),
        ("testSelectLT", testSelectLT),
    ]
}

extension IProtoSchemaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IProtoSchemaTests = [
        ("testCreateSpace", testCreateSpace),
        ("testSchema", testSchema),
    ]
}

extension IProtoSpaceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IProtoSpaceTests = [
        ("testCount", testCount),
        ("testDelete", testDelete),
        ("testGet", testGet),
        ("testInsert", testInsert),
        ("testReplace", testReplace),
        ("testSelect", testSelect),
        ("testSequence", testSequence),
        ("testUpdate", testUpdate),
        ("testUpsert", testUpsert),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CHAPSHA1Tests.__allTests__CHAPSHA1Tests),
        testCase(IProtoConnectionTests.__allTests__IProtoConnectionTests),
        testCase(IProtoDataSourceTests.__allTests__IProtoDataSourceTests),
        testCase(IProtoIndexTests.__allTests__IProtoIndexTests),
        testCase(IProtoIteratorTests.__allTests__IProtoIteratorTests),
        testCase(IProtoSchemaTests.__allTests__IProtoSchemaTests),
        testCase(IProtoSpaceTests.__allTests__IProtoSpaceTests),
    ]
}
#endif
