#if !canImport(ObjectiveC)
import XCTest

extension TestUtilsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestUtilsTests = [
        ("testModulePath", testModulePath),
        ("testTarantoolProcess", testTarantoolProcess),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TestUtilsTests.__allTests__TestUtilsTests),
    ]
}
#endif
